font:
  # normal:
  #   family: Operator Mono
  #   style: Book

  # bold:
  #   family: Operator Mono
  #   style: Bold

  # italic:
  #   family: Operator Mono
  #   style: Italic

  # bold_italic:
  #   family: Operator Mono
  #   style: Medium Italic

  normal:
    family: JetBrainsMono NF
    style: Regular

  bold:
    family: JetBrainsMono NF
    style: Bold

  italic:
    family: JetBrainsMono NF
    style: Italic

  bold_italic:
    family: JetBrainsMono NF
    style: Medium Italic

  size: 15
